Repository atlp-rwanda/e-comm-team-techsmith-bn, pull requests merged in 2023-04, with the labels that each got.

#18 #184752079 Ch integrate coveralls
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/test/login.test.js
Labels: ready

#30 #184779985 Create Pull Request Template File
  .github/pull_request_template.md
Labels: ready

#27 #184752089 Ch login authentification
  database/config/config.js
  database/models/cart.js
  database/models/category.js
  database/models/order.js
  database/models/payment.js
  database/models/product.js
  database/models/role.js
  database/models/user.js
  database/seeders/20230330003155-demo-user.js
  package-lock.json
  package.json
  src/controller/loginController.js
  src/routes/allRoutes.js
  src/routes/loginRoute.js
  src/test/login.test.js
Labels: WIP, ready

#33 #184752086 Providing descriptive messages to users
  .nyc_output/processinfo/index.json
  database/config/config.js
  package-lock.json
  package.json
  src/controller/loginController.js
  src/controller/signupController.js
  src/docs/User/userLogin.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/allRoutes.js
  src/routes/loginRoute.js
  src/routes/userRoute.js
  src/test/app.test.js
  src/test/login.test.js
  src/test/signup.test.js
  src/utils/userValidation.js
Labels: ready

#36 #184842347 Implement Newsletter Signup
  .circleci/config.yml
  .nyc_output/processinfo/index.json
  database/migrations/20230330155402-create-role.js
  database/migrations/20230405001904-create-subscription.js
  database/migrations/20230405141727-create-user.js
  database/models/subscription.js
  database/models/user.js
  database/seeders/20230330003155-demo-user.js
  database/seeders/20230330160123-demo-role.js
  database/seeders/20230330160128-demo-user.js
  database/seeders/20230405002314-demo-subscription.js
  src/controller/loginController.js
  src/controller/newsletterController.js
  src/controller/signupController.js
  src/docs/User/userNewsletter.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/userRoute.js
  src/test/login.test.js
  src/test/newsletter.test.js
  src/test/signup.test.js
  src/utils/emails.js
Labels: ready

#22 #184752092: ft-reset-password
  .circleci/config.yml
  .env.example
  .eslintrc.json
  .nyc_output/processinfo/index.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/database/config/config.js.html
  coverage/lcov-report/database/config/index.html
  coverage/lcov-report/database/models/index.html
  coverage/lcov-report/database/models/index.js.html
  coverage/lcov-report/database/models/user.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/controller/index.html
  coverage/lcov-report/src/controller/resetPassword.js.html
  coverage/lcov-report/src/controller/userController.js.html
  coverage/lcov-report/src/docs/Product/getProducts.js.html
  coverage/lcov-report/src/docs/Product/index.html
  coverage/lcov-report/src/docs/components.js.html
  coverage/lcov-report/src/docs/index.html
  coverage/lcov-report/src/docs/index.js.html
  coverage/lcov-report/src/docs/paths.js.html
  coverage/lcov-report/src/docs/resetPassword.js.html
  coverage/lcov-report/src/docs/servers.js.html
  coverage/lcov-report/src/docs/tags.js.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/routes/allRoutes.js.html
  coverage/lcov-report/src/routes/index.html
  coverage/lcov-report/src/routes/resetPasswordRoute.js.html
  coverage/lcov-report/src/routes/swaggerRoute.js.html
  coverage/lcov-report/src/routes/userRoute.js.html
  coverage/lcov-report/src/server.js.html
  coverage/lcov.info
  database/migrations/20230405141727-create-user.js
  database/models/index.js
  database/models/user.js
  database/seeders/20230330003155-demo-user.js
  package-lock.json
  package.json
  src/controller/resetPassword.js
  src/docs/paths.js
  src/docs/resetPassword.js
  src/routes/allRoutes.js
  src/routes/resetPasswordRoute.js
  src/server.js
  src/test/login.test.js
  src/test/passwordReset.test.js
  src/test/signup.test.js
Labels: ready

#31 #184752097 Updating user password
  .circleci/config.yml
  .env.example
  .gitignore
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/database/config/config.js.html
  coverage/lcov-report/database/config/index.html
  coverage/lcov-report/database/models/index.html
  coverage/lcov-report/database/models/index.js.html
  coverage/lcov-report/database/models/user.js.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/controller/index.html
  coverage/lcov-report/src/controller/resetPassword.js.html
  coverage/lcov-report/src/controller/userController.js.html
  coverage/lcov-report/src/docs/Product/getProducts.js.html
  coverage/lcov-report/src/docs/Product/index.html
  coverage/lcov-report/src/docs/components.js.html
  coverage/lcov-report/src/docs/index.html
  coverage/lcov-report/src/docs/index.js.html
  coverage/lcov-report/src/docs/paths.js.html
  coverage/lcov-report/src/docs/resetPassword.js.html
  coverage/lcov-report/src/docs/servers.js.html
  coverage/lcov-report/src/docs/tags.js.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/routes/allRoutes.js.html
  coverage/lcov-report/src/routes/index.html
  coverage/lcov-report/src/routes/resetPasswordRoute.js.html
  coverage/lcov-report/src/routes/swaggerRoute.js.html
  coverage/lcov-report/src/routes/userRoute.js.html
  coverage/lcov-report/src/server.js.html
  coverage/lcov.info
  database/models/cart.js
  database/models/category.js
  database/models/order.js
  database/models/payment.js
  database/models/product.js
  database/models/role.js
  database/seeders/20230401072240-demo-user.js
  database/seeders/20230401072343-demo-role.js
  package-lock.json
  package.json
  src/controller/userController.js
  src/docs/User/updatePassword.js
  src/docs/User/userSignup.js
  src/docs/paths.js
  src/docs/tags.js
  src/routes/userRoute.js
  src/test/login.test.js
  src/test/passwordReset.test.js
  src/test/update.test.js
Labels: ready

#34 #184752090 Ft Login with Google
  .env.example
  database/migrations/20230405141727-create-user.js
  database/models/user.js
  database/seeders/20230407175713-demo-user.js
  package-lock.json
  package.json
  src/controller/newsletterController.js
  src/docs/User/googleAuth.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/allRoutes.js
  src/routes/auth.js
  src/server.js
  src/test/login.test.js
Labels: ready

#43 #184797947 Admin should be able get all orders …
  src/controller/loginController.js
  src/controller/newsletterController.js
  src/controller/orderController.js
  src/controller/resetPassword.js
  src/controller/signupController.js
  src/docs/Order/order.js
  src/docs/components.js
  src/docs/paths.js
  src/docs/tags.js
  src/middleware/verifyIsAdmin.js
  src/routes/allRoutes.js
  src/routes/auth.js
  src/routes/orderRoute.js
  src/test/newsletter.test.js
  src/test/order.test.js
Labels: ready

#44 #184902405 RF Removing Console.log On Develop
  database/seeders/20230331090218-demo-Order.js
  package.json
  src/controller/userController.js
  src/routes/auth.js
  src/server.js
  src/utils/emails.js
Labels: ready

#41 #184752112 Payments feature using Stripe API
  .env.example
  database/migrations/20230330203158-create-payment.js
  database/models/payment.js
  database/seeders/20230330003155-demo-user.js
  database/seeders/20230330160123-demo-role.js
  database/seeders/20230330160128-demo-user.js
  database/seeders/20230330212636-demo-role.js
  database/seeders/20230330215541-demo-product.js
  database/seeders/20230330224039-demo-Category.js
  database/seeders/20230331090218-demo-Order.js
  database/seeders/20230331090448-demo-Cart.js
  database/seeders/20230331090519-demo-Payment.js
  database/seeders/20230401072240-demo-user.js
  database/seeders/20230401072343-demo-role.js
  package-lock.json
  package.json
  src/controllers/loginController.js
  src/controllers/newsletterController.js
  src/controllers/orderController.js
  src/controllers/paymentsController.js
  src/controllers/resetPassword.js
  src/controllers/signupController.js
  src/controllers/userController.js
  src/docs/Payment/createPayment.js
  src/docs/components.js
  src/docs/paths.js
  src/middlewares/validatePayment.js
  src/middlewares/verifyIsAdmin.js
  src/routes/auth.js
  src/routes/orderRoute.js
  src/routes/resetPasswordRoute.js
  src/routes/userRoute.js
  src/test/payment.test.js
  src/test/update.test.js
  src/utils/cookies.js
  src/utils/emails.js
Labels: ready

#37 #184752093 two-factor-authentication-for-seller
  package-lock.json
  package.json
  src/controllers/loginController.js
  src/controllers/newsletterController.js
  src/controllers/resetPassword.js
  src/controllers/signupController.js
  src/docs/User/userLogin.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/userRoute.js
  src/test/login.test.js
  src/test/payment.test.js
  src/utils/emails.js
Labels: WIP

#40 #184752088 Logout Functionality
  .circleci/config.yml
  src/controllers/userController.js
  src/routes/userRoute.js
  src/test/logout.test.js
  src/test/passwordReset.test.js
Labels: ready

#46 #184752098 User with seller as a Role can Add product #35
  .env.example
  database/migrations/20230330194957-create-product.js
  database/models/product.js
  package-lock.json
  package.json
  src/controllers/productController.js
  src/controllers/userController.js
  src/docs/Product/addProduct.js
  src/docs/Product/getProducts.js
  src/docs/components.js
  src/docs/paths.js
  src/middlewares/isActiveUser.js
  src/routes/allRoutes.js
  src/routes/auth.js
  src/routes/productRoutes.js
  src/server.js
  src/test/order.test.js
  src/test/passwordReset.test.js
  src/test/product.test.js
  src/test/signup.test.js
  src/utils/emails.js
  src/utils/productValidation.js
Labels: ready

#39 #184752094 Getting and Updating Users
  package-lock.json
  src/controllers/loginController.js
  src/controllers/userController.js
  src/docs/User/updateUser.js
  src/docs/User/userSignup.js
  src/docs/components.js
  src/docs/paths.js
  src/middlewares/checkIsLoggedIn.js
  src/routes/userRoute.js
  src/test/passwordReset.test.js
  src/test/profile.test.js
  src/test/update.test.js
  src/utils/emails.js
Labels: ready

#42 #184752095 Admin should be able to disable an account
  src/controllers/disEnableUser.js
  src/docs/Admin/disableUser.js
  src/docs/Admin/enableUser.js
  src/docs/paths.js
  src/docs/tags.js
  src/middlewares/ensureIsEnabled.js
  src/routes/userRoute.js
  src/test/disable.test.js
  src/utils/emails.js
Labels: ready

#45 feature(crud): CRUD users by Admin
  src/controllers/adminController.js
  src/docs/Admin/createUser.js
  src/docs/Admin/deleteUser.js
  src/docs/Admin/enableUser.js
  src/docs/Admin/getUsers.js
  src/docs/Admin/updateUser.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/adminRoute.js
  src/routes/allRoutes.js
  src/test/crudUser.test.js
Labels: ready

#48 bug(bug-fixing): Bug fixing on all branches
  src/controllers/adminController.js
  src/controllers/loginController.js
  src/controllers/newsletterController.js
  src/controllers/orderController.js
  src/controllers/paymentsController.js
  src/controllers/productController.js
  src/controllers/resetPassword.js
  src/controllers/signupController.js
  src/controllers/userController.js
  src/docs/components.js
  src/docs/paths.js
  src/middlewares/activeUser.js
  src/middlewares/checkIsLoggedIn.js
  src/middlewares/ensureIsEnabled.js
  src/middlewares/isActiveUser.js
  src/middlewares/validatePayment.js
  src/middlewares/verifyIsAdmin.js
  src/middlewares/verifyIsSeller.js
  src/routes/adminRoute.js
  src/routes/allRoutes.js
  src/routes/orderRoute.js
  src/routes/productRoutes.js
  src/routes/resetPasswordRoute.js
  src/routes/sampleRoute.js
  src/routes/userRoute.js
  src/routes/welcomeRoute.js
  src/test/app.test.js
  src/test/crudUser.test.js
  src/test/newsletter.test.js
  src/test/order.test.js
  src/test/passwordReset.test.js
  src/test/product.test.js
  src/test/profile.test.js
  src/test/update.test.js
  src/utils/cookies.js
  src/utils/emails.js
  src/utils/userInfo.js
Labels: ready

#51 #184752104 A buyer should be able to add a product to wish list
  database/models/cart.js
  database/models/product.js
  package-lock.json
  package.json
  src/controllers/addProductToWishlistController.js
  src/docs/Wishlist/addProductToWishlist.js
  src/docs/components.js
  src/docs/paths.js
  src/docs/tags.js
  src/middlewares/verifyIsBuyer.js
  src/routes/allRoutes.js
  src/routes/productRoutes.js
  src/routes/wishlistRoute.js
  src/test/addProductToWishlist.test.js
Labels: ready

#63 [#184752115] Ft check expiration of products
  package.json
  src/controllers/addProductToWishlistController.js
  src/controllers/productController.js
  src/docs/Product/checkExpirationOfProduct.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/productRoutes.js
  src/server.js
  src/test/crudUser.test.js
  src/test/product.test.js
  src/utils/emails.js
  src/utils/getIdAndDate.js
  src/utils/shedulerController.js
Labels: ready

#64 #184829218 Admin changes the status of delivered or cancelled
  database/models/cart.js
  src/controllers/deliveredOrderController.js
  src/docs/Order/cancelled.js
  src/docs/Order/delivered.js
  src/docs/User/userLogout.js
  src/docs/paths.js
  src/middlewares/isSellerOrAdmin.js
  src/routes/orderRoute.js
  src/routes/userRoute.js
  src/server.js
  src/test/deliverAndCancel.test.js
  src/test/disable.test.js
  src/utils/emails.js
  src/utils/shedulerController.js
Labels: ready

#57 #184797945 CRUD operations on order
  src/controllers/orderController.js
  src/docs/Order/createOrder.js
  src/docs/Order/deleteOrder.js
  src/docs/Order/updateOrder.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/orderRoute.js
  src/test/order.test.js
Labels: ready

#59 #184752110 user can search a product
  src/controllers/productController.js
  src/docs/Product/searchProduct.js
  src/docs/Product/updateAproduct.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/productRoutes.js
  src/test/product.test.js
  src/utils/productSearch.js
Labels: ready

#60 #184752106 User/buyer should be able to add items to their cart
  src/controllers/cartController.js
  src/controllers/wishlistController.js
  src/docs/Cart/addItemInCart.js
  src/docs/Product/createProduct.js
  src/docs/Product/getAllMyProducts.js
  src/docs/Product/getProductsInStock.js
  src/docs/components.js
  src/docs/paths.js
  src/docs/tags.js
  src/routes/allRoutes.js
  src/routes/cartRoute.js
  src/test/cart.test.js
  src/workers/wishlist.js
Labels: ready

#68 184752108 Buyer should be able to view their cart
  database/models/cart.js
  database/models/user.js
  src/controllers/cartController.js
  src/docs/Cart/viewItemsInCart.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/cartRoute.js
  src/test/cart.test.js
Labels: ready

#52 #184752118 Public real-time chatroom for users
  .github/pull_request_template.md
  database/migrations/20230420150024-create-chat.js
  database/migrations/20230420224750-user-column.js
  database/migrations/20230422231205-create-activity.js
  database/models/activity.js
  database/models/chat.js
  database/models/user.js
  database/seeders/20230420150928-demo-chats.js
  package-lock.json
  package.json
  src/controllers/chatroomController.js
  src/controllers/paymentsController.js
  src/controllers/userController.js
  src/docs/Product/searchProduct.js
  src/middlewares/checkIsLoggedIn.js
  src/middlewares/isSellerOrAdmin.js
  src/middlewares/validatePayment.js
  src/middlewares/verifyIsAdmin.js
  src/middlewares/verifyIsBuyer.js
  src/middlewares/verifyIsSeller.js
  src/routes/allRoutes.js
  src/routes/paymentRoute.js
  src/server.js
  src/test/change.role.test.js
  src/test/chatroom.test.js
  src/test/logout.test.js
  src/test/payment.test.js
  src/test/product.test.js
  src/test/profile.test.js
  src/test/update.test.js
  src/utils/cookies.js
  src/views/assets/chat.css
  src/views/assets/chat.js
  src/views/assets/login.js
  src/views/assets/main.css
  src/views/assets/main.js
  src/views/assets/style.css
  src/views/chat.html
  src/views/index.html
Labels: ready

#53 #184752101 user can view specific item
  .env.example
  src/controllers/adminCRUDproduct.js
  src/controllers/productController.js
  src/controllers/resetPassword.js
  src/docs/Admin/getASingleProduct.js
  src/docs/Product/getProducts.js
  src/docs/paths.js
  src/docs/resetPassword.js
  src/docs/tags.js
  src/middlewares/checkIsLoggedIn.js
  src/routes/adminRoute.js
  src/routes/productRoutes.js
  src/test/login.test.js
  src/test/product.test.js
Labels: ready

#79 #185026102 Feature to get all products and delete products from wish list.
  database/migrations/20230426090249-create-wishlist.js
  database/models/wishlist.js
  package-lock.json
  src/controllers/wishlistController.js
  src/docs/Wishlist/deleteProductToWishlist.js
  src/docs/Wishlist/getAllProductToWishlist.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/wishlistRoute.js
  src/test/addProductToWishlist.test.js
Labels: ready

#85 #004 Fixing Admin Product Creation
  src/controllers/adminCRUDproduct.js
  src/docs/Admin/createProduct.js
  src/docs/components.js
  src/test/order.test.js
  src/test/product.test.js
  src/utils/productValidation.js
Labels: ready

#77 #184752107 Buyer should be able to update their cart
  database/migrations/20230330202931-create-cart.js
  database/migrations/20230426142920-20230330194957-create-product.js.js
  database/migrations/20230426233632-modifyColumn.js
  database/models/cart.js
  database/models/order.js
  database/models/product.js
  src/controllers/adminCRUDproduct.js
  src/controllers/cartController.js
  src/controllers/orderController.js
  src/controllers/productController.js
  src/controllers/wishlistController.js
  src/docs/Cart/updateItemsInCart.js
  src/docs/Order/createOrder.js
  src/docs/Order/deleteOrder.js
  src/docs/Order/updateOrder.js
  src/docs/components.js
  src/docs/paths.js
  src/routes/cartRoute.js
  src/test/addProductToWishlist.test.js
  src/test/cart.test.js
  src/test/feedback.test.js
  src/test/order.test.js
  src/utils/productValidation.js
  src/utils/validateQuantity.js
Labels: ready

#81 #184752113 Buyer is able to checkout
  database/seeders/20230331090218-demo-Order.js
  package-lock.json
  src/controllers/cartController.js
  src/controllers/disEnableUser.js
  src/controllers/paymentsController.js
  src/controllers/productController.js
  src/controllers/wishlistController.js
  src/middlewares/validatePayment.js
  src/routes/orderRoute.js
  src/routes/paymentRoute.js
  src/test/order.test.js
  src/test/payment.test.js
  src/utils/emails.js
Labels: ready
